### ISSUE TITLE
compiling on Windows

### ISSUE THREAD

**Issue by lornemartin** [darkk/redsocks#103]
I am wondering about the feaseability of using this project as a Windows proxifier such as [ProxyCap](http://www.proxycap.com/) or [Proxifier](https://www.proxifier.com/). So before I invest much time in it I would like to know,  is there a technical reason that no one has ported this to Windows, or has there just not been any call for it?

**Comment by darkk** [comment]
>  is there a technical reason that no one has ported this to Windows

I have no permanent root access to machines running Windows to test and develop for these platforms. Moreover, I'm unsure if that's possible. [`squid` does not support transparent-proxy mode on windows](https://wiki.squid-cache.org/KnowledgeBase/Windows):

> Squid features not operational:
> Transparent Proxy: missing Windows non commercial interception driver 

So, it seems to me, it's not possible.

**Comment by haohaolee** [comment]
Actually, there is one interception driver called WinDivert https://reqrypt.org/windivert.html with LGPL license
