### ISSUE TITLE
dns through http proxy

### ISSUE THREAD

**Issue by gilcu3** [darkk/redsocks#104]
I don't really know whether redsocks supports this or not, and can't deduce it from docs (although maybe it's clear and I'm dumb). I'm behind an http proxy server with digest auth (squid), but the network doesn't have a dns resolver, everything is done by the proxy, after authenticated of course. Is it possible to use redsocks in this environment? Maybe with some redup section?

**Comment by darkk** [comment]
I'm not sure if the answer is still relevant... But There are basically three options:

- enforce DNS request over TCP (if client supports that), that's done with `dnstc` module
- convert DNS/UDP to DNS/TCP and pass it through proxy, that's done with `dnsu2t` module
- "avoid" passing DNS request packet through proxy and pass FQDN to the proxy server, that's discussed in #23
