### ISSUE TITLE
Cannot get any response and reached redsocks_conn_max limit

### ISSUE THREAD

**Issue by CROSP** [darkk/redsocks#108]
Hi, I have encountered the following problem. I have set up redsocks (compiled it) and added the following Iptables rules

```
iptables -t nat -N REDSOCKS
iptables -t nat -A REDSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A REDSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A REDSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A REDSOCKS -d 240.0.0.0/4 -j RETURN
iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports 12345
iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner root -j REDSOCKS

```

Here is my configuration file

```
base {
        log_info = on;
        daemon = off;
        log_debug = on;
        log = stderr;
        redirector = iptables;
 }

redsocks {
        local_port = 12345;
        local_ip = 127.0.0.1;
        ip = proxy.ip.address;
        port = proxy.port;
        login = loginname;
        password = password;
        type = socks5;
 }

```

It doesn't work, it hangs on a request and I get the following output in debug mode

```
[root@centos redsocks]# ./redsocks -c /etc/redsocks.conf
1499805653.423018 notice main.c:165 main(...) redsocks started, conn_max=128
1499805681.417363 info redsocks.c:1243 redsocks_accept_client(...) [192.168.0.128:44854->174.129.241.106:443]: accepted
1499805681.417478 info redsocks.c:1243 redsocks_accept_client(...) [192.168.0.128:35878->1 proxy.ip.address:proxy.port]: accepted
1499805681.417539 info redsocks.c:1243 redsocks_accept_client(...) [192.168.0.128:35880-> proxy.ip.address:proxy.port]: accepted
1499805681.417606 info redsocks.c:1243 redsocks_accept_client(...) [192.168.0.128:35882-> proxy.ip.address:proxy.port]: accepted
......
1499805681.424992 warning redsocks.c:1141 redsocks_conn_list_add(...) reached redsocks_conn_max limit, 128 connections
1499805681.425060 warning redsocks.c:1045 conn_pressure(...) accept: backing off for 0.001000s
1499805681.425074 info redsocks.c:1243 redsocks_accept_client(...) [192.168.0.128:36130-> proxy.ip.address:proxy.port]: accepted
1499805681.426237 warning redsocks.c:1045 conn_pressure(...) accept: backing off for 0.002000s
1499805681.428329 warning redsocks.c:1045 conn_pressure(...) accept: backing off for 0.005000s
1499805681.433419 warning redsocks.c:1045 conn_pressure(...) accept: backing off for 0.009000s
.....
....
```

What could be wrong with it ? Why I cannot get any response. It doesn't what type of request I made, it hangs and that's all. As an example 

`curl 'https://api.ipify.org?format=json'
`

Proxy is 100% working 

Could you help with that issue.

**Comment by CROSP** [comment]
I got the similar behavior using the fork https://github.com/semigodking/redsocks

**Comment by darkk** [comment]
What is your redsocks version? What does `redsocks -v` day?

**Comment by darkk** [comment]
@CROSP actually, you have a bug in your `iptables` ruleset, it's redirecting `redsocks` daemon back to itself.

`[root@centos redsocks]# ./redsocks -c /etc/redsocks.conf` shows `#` sign, so I assume that you run redsocks as `root` user. Your iptables rule `iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner root -j REDSOCKS` redirects traffic from redsocks back to redsocks itself, so there is a loop and you max out the count of connections within several milliseconds :-)

**Comment by CROSP** [comment]
Thank you for the prompt answer
```
[root@centos redsocks]# ./redsocks -v
redsocks.git/release-0.5
Built with libevent-2.0.21-stable
Runs  with libevent-2.0.21-stable
```

**Comment by chengen** [comment]
I ran into this problem this afternoon, and it took me several hours to figure it out.  I suggest add it int to beginner's guide. Do run redsocks  and curl test on different user and don't send the traffic of the user who is running redsocks to itself. 
Thanks.

**Comment by darkk** [comment]
@chengen `redsocks` should log following line when you restart `redsocks` instance that has alike bug in iptables ruleset configuration:
`notice redsocks_drop_client(...) [A.B.C.D:PP->X.Y.Z.W:QQ]: client tries to connect to the proxy using proxy! Usual proxy security policy is to drop alike connection`
That was introduced in 42977373b9b37da1b8f97afbe2ea5b7627074e12.
