### ISSUE TITLE
How to resolve hostnames through proxy?

### ISSUE THREAD

**Issue by blake29** [darkk/redsocks#113]
How to resolve dns through socks5 ? because when i go to ipleak.net or whoer.com it shows my isp dns. How can i resolve hostnames through proxy? (the proxy has dns with ability to resolve dns and i checked it with proxifier in windows and it worked fine)
Please answer the solution in detail.
Thanks in advance

**Comment by darkk** [comment]
Here are possible options: https://github.com/darkk/redsocks#enforcing-dns-over-tcp-using-dnstc
`dnstc` will probably give a bit better performance.

Also, if you care about location leaks, "just using socks5 proxy" is probably not enough for lots of possible reasons.
