### ISSUE TITLE
Accessing rubygems.org throughout redsocks fails

### ISSUE THREAD

**Issue by matlo607** [darkk/redsocks#117]
Redsocks converts the server name to its ip address.
rubygems.org --> https://151.101.66.2/ and the connection fails with `Unable to establish SSL connection`

With redsocks :
```
# wget https://rubygems.org/
--2018-02-23 15:23:05--  https://rubygems.org/
Resolving rubygems.org (rubygems.org)... 151.101.66.2, 151.101.130.2, 151.101.194.2, ...
Connecting to rubygems.org (rubygems.org)|151.101.66.2|:443... connected.
Unable to establish SSL connection.
```

Without redsocks and the proxy variable set :
```
# https_proxy="https://proxy:3128" wget https://rubygems.org/
--2018-02-23 15:23:25--  https://rubygems.org/
Resolving proxy (proxy)... X.X.X.X
Connecting to proxy (proxy)|X.X.X.X|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’
index.html                       [ <=> ]  10.94K  --.-KB/s    in 0s      
2018-02-23 15:23:26 (73.6 MB/s) - ‘index.html’ saved [11203]
```

Actually accessing rubygems.org with its ip address fails proxy or not.
Is there a way to prevent redsocks from replacing server names by their ip ?

**Comment by darkk** [comment]
That's policy of proxy server that denies `CONNECT 151.101.66.2:443 HTTP/1.0` request and allows `CONNECT rubygems.org:443 HTTP/1.0` request.
It's impossible to make a transparent proxy that _reliably_ guesses correct domain name in 100% of cases. There are some possible improvements, they're discussed in #23
