### ISSUE TITLE
Not working on https proxy

### ISSUE THREAD

**Issue by chengen** [darkk/redsocks#128]
Hi, guys. I run redsocks on centos7, it works pretty good while connecting squid proxy.   But when I switch to https proxy. It is not working.  There is no problem  on the https proxy servers, it works good on browser proxy settings.  
**here is my redsocks configuration, connecting remote https server :** 
 99   ip = my.proxy.domain;
100   port = 443;
101
102   // known types: socks4, socks5, http-connect, http-relay
103   type = http-connect;
104
105   login = "user";
106   password = "pass.";

**here is the redsocks error info:**

1528720500.285711 info redsocks.c:1243 redsocks_accept_client(...) [10.0.3.15:42352->74.208.236.169:80]: accepted
1528720500.416665 notice redsocks.c:839 redsocks_event_error(...) [10.0.3.15:42352->74.208.236.169:80]: relay error, code EVBUFFER_READ|0|0|EVBUFFER_ERROR|0|0x0: Connection reset by peer
1528720500.416693 info redsocks.c:689 redsocks_drop_client(...) [10.0.3.15:42352->74.208.236.169:80]: dropping client (R/W), relay (R/W), idle 0.000060s

**here is the remote https proxy error:**

2018.06.11 22:14:28 LOG5[25735:139673099814656]: squid accepted connection from 114.252.49.76:60762
2018.06.11 22:14:28 LOG7[25735:139673099814656]: SSL state (accept): before/accept initialization
2018.06.11 22:14:28 LOG3[25735:139673099814656]: SSL_accept: 1407609B: error:1407609B:SSL routines:SSL23_GET_CLIENT_HELLO:https proxy request
2018.06.11 22:14:28 LOG5[25735:139673099814656]: Connection reset: 0 bytes sent to SSL, 0 bytes sent to socket
2018.06.11 22:14:28 LOG7[25735:139673099814656]: squid finished (0 left)

**here is my version:**
redsocks.git/release-0.5-7-g5df6a30
Built with libevent-2.0.21-stable
Runs  with libevent-2.0.21-stable

My current solution is run stunnel client at local to connect remote https server.  And then configure redsocks to connect local stunnel. It work fine, but I wan't to get rid of stunnel and use redsocks connect remote https server directly.

 99   ip = 127.0.0.1;
100   port = 1080; //local stunnel client 
101
102   // known types: socks4, socks5, http-connect, http-relay
103   type = http-connect;
104
105   login = "user";
106   password = "pass.";

Thank you for your time!

**Comment by chengen** [comment]
I switch to to forked version  of https://github.com/semigodking/redsocks , and use https_connect, problem solved.  This version does not support https proxy. 

Thank you all the same.

**Comment by darkk** [comment]
Yes, https is not supported. New features will unlikely be implemented within this source tree in near future. I'm not redsocks user nowadays, so I have no reason to develop new non-trivial features, I'm just fixing bugs :-)

Zhuofei Wang has done an awesome fork `redsocks2` and Zhuofei maintains the fork. I've mentioned it in README:

> New network protocols will unlikely be implemented within this source tree, but if you're seeking for censorship circumvention protocols, you may want to take a look at [redsocks2](https://github.com/semigodking/redsocks) by Zhuofei Wang AKA @semigodking who is actively maintaining the fork with GFW in mind.
