### ISSUE TITLE
Redsocks doesn't redirect

### ISSUE THREAD

**Issue by Mahdi321** [darkk/redsocks#135]
Redsocks doesn't redirect traffic
OS: ubuntu 18.04

**Comment by darkk** [comment]
`redsocks` indeed does not redirect traffic.
`redsocks` handles traffic redirected by the means of kernel, namely, netfilter subsystem configured via iptables (or more modern variant of it).
As soon as `redsocks` is not redirecting any traffic, I assume, it's not a bug :man_shrugging:
