### ISSUE TITLE
UDP/Tracepath  Traffic redirection

### ISSUE THREAD

**Issue by hbtechnologia** [darkk/redsocks#148]
How can i redirect all udp traffic through redsocks like tracepath, icmp,ping echo etc ?

**Comment by mirfatif** [comment]
ICMP, ping, echo is ICMP, not UDP. You need a VPN for that.

**Comment by hbtechnologia** [comment]
i have shadowsocks server

**Comment by mirfatif** [comment]
Shadowsocks is SOCKS5 proxy which can carry TCP or UDP traffic. `redsocks` can redirect all UDP traffic provided that proxy server supports UDP associate feature. Not all SOCKS5 proxies do, but `shadowsocks` does. And they have `ss-redir` tool for the same purpose. See the manpage.

ICMP/ping/echo is a different protocol, not UDP (though pinging is possible with UDP too). It operate at lower level in network stack. So you need a low level protocol such as those used by VPN. See https://serverfault.com/questions/177561/sending-icmp-request-with-proxy

**Comment by hbtechnologia** [comment]
Thanks for your help appreciated your quick response.
