### ISSUE TITLE
What is the difference between http-relay and http-connect?

### ISSUE THREAD

**Issue by copbint** [darkk/redsocks#154]
Hi,
I have googled a lot, but failed to figure it out. 

Any suggestions would be greatly appreciated!

**Comment by darkk** [comment]
`http-relay` and `http-relay` are the same thing. :slightly_smiling_face: 

Do you mean `http-relay` and `http-something-else` ?

**Comment by copbint** [comment]
Oh, I'm really sorry to make such a mistake。
I mean `http-relay` and `http-connect`.

**Comment by jeremiehuchet** [comment]
Assuming you have a proxy listening on port `3128` on IP address `<PROXY_IP>`.  
When you execute the follwing command : `curl http://perdu.com:80`,

A redsocks **http-relay** will dial `<PROXY_IP>:3128` and write the HTTP request. Your proxy will open a TCP connection with perdu.com on port 80 and write the HTTP request.
In this case the proxy server can parse the request headers and perform caching or other features at HTTP protocol level.

A redsocks **http-connect** will dial `<PROXY_IP>:3128`, write `CONNECT perdu.com:80 HTTP/1.1`. Your proxy will open a TCP connection with perdu.com on port 80 and forward everything the client sends to the proxy. In this example, it will forward the HTTP request but it won't be able to parse the request headers.  
In this case, the proxy server don't look at the forwarded data. It can't perform caching, but it allows the client to communicate through the proxy using any protocol (SSH, HTTPS, ...) as long as the proxy's ACL are allowing such trafic.

**Comment by copbint** [comment]
Amazing explanation, clear enough!  Many thanks!
