### ISSUE TITLE
Use redsocks to achieve the p2p live video streaming for remote driverless vehicle surveillance.

### ISSUE THREAD

**Issue by hongyi-zhao** [darkk/redsocks#158]
I am currently involved in a remote monitoring project for a driverless vehicle. In this project, the camera is installed on the driverless vehicle working in the wild, at the meanwhile, the live video is transferred by specific streaming protocol to the monitor of the client side. Both the vehicle and client are connected to the internet through 4G LTE sim cards.

For the scenario described above, can redsocks be used to achieve the p2p live video streaming for remote driverless vehicle surveillance?

Any hints will be highly appreciated.

Regards,
HY

**Comment by darkk** [comment]
According to the best of my understanding, `redsocks` is absolutely irrelevant to your use-case.
