### ISSUE TITLE
Log file permission denied 

### ISSUE THREAD

**Issue by olegZmemer** [darkk/redsocks#166]
`1647518172.794082 err log.c:145 log_preopen(...) log_preopen(file:/tmp/reddi.log, ...): Permission denied`

When _./redsocks -c redsocks.conf_
![2022-03-17_15-01](https://user-images.githubusercontent.com/41783744/158804506-69a92d5e-d917-4ccf-aefe-0eb84a960dc2.png)

**Comment by darkk** [comment]
:man_shrugging: 

That looks like some kind of selinux / apparmor / LSM or other security-hardening issue to me.

**Comment by olegZmemer** [comment]
@darkk I fixed it by adding command that removes old reddi.log after stopping _redsocks_
also thanks for your programm it's very helpful!
