### ISSUE TITLE
Using REDSOCKS

### ISSUE THREAD

**Issue by su966** [darkk/redsocks#39]
I have installed REDSOCKS on latest ubuntu server. It has two interfaces

Client (192.168.1.21/24) -->int eth1(192.168.1.1/24) of Ubuntu server --Redsocks --int eth0(172.18.185.14/22) of Ubuntu Server -->ISP Proxy (172.28.21.240:8080) -->Internet

Client does not have the ability to configure proxy server
Redsocks.conf file
 base{
          log_debug=on;
          log_info=on;
          log= "syslog:daemon";
          daemon=on;
          redirector=iptables;
}
redsocks {
           local_ip=192.168.1.1;
           local_port=12345;
           ip=172.28.21.240;
           port=8080;
           type=socks5;
}

Contents of iptables
*nat
:PREROUTING ACCEPT[217:36158]
:INPUT ACCEPT [1147:90444]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT[0:0]
:REDSOCKS - [0:0]

-A PREROUTING -i eth1 -p tcp -j REDSOCKS
-A POSTROUTING -o eth0 -j MASQUERADE
-A REDSOCKS -d 0.0.0.0/8 -j RETURN
-A REDSOCKS -d 127.0.0.0/8 -j RETURN
-A REDSOCKS -d 192.168.0.0/16 RETURN
-A REDSOCKS -p tcp -j REDIRECT --to-ports 12345

*filter
:INPUT ACCEPT [10732:923988]
:FORWARD ACCEPT[581:108005]
:OUTPUT ACCEPT[7693:310754]
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
COMMIT

With the above configuration client can not access internet.

Please give some help.

**Comment by drvirusz** [comment]
i have an issue with my redsocks , im unable to use it with anything
=============

root@VPNSOCKS:~# redsocks -v
redsocks/0.4
root@VPNSOCKS:~# dpkg -l redsocks
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                          Version             Architecture        Description
+++-=============================-===================-===================-================================================================
ii  redsocks                      0.4+dfsg-2          i386                arbitrary TCP connection redirector to a SOCKS or HTTPS proxy se
root@VPNSOCKS:~# 

===================================

redsocks logs , always either started or stopped !! no more logs

1438684502.226839 main.c:152 main(...) redsocks started
1438684594.838973 main.c:156 main(...) redsocks goes down
1438684594.876312 main.c:152 main(...) redsocks started
1438685072.148543 main.c:156 main(...) redsocks goes down


i have ubuntu 14 / installed with redsocks and i have about 2 socks servers that authorize my server public ip.

i 2 private subnets
192.168.10.0/24
and
192.168.20.0/24

root@VPNSOCKS:~# ifconfig
eth0 Link encap:Ethernet HWaddr 04:01:61:49:10:01 
inet addr:xxxxx.231.2 Bcast:104.236.255.255 Mask:255.255.192.0
inet6 addr: fe80::601:61ff:fe49:1001/64 Scope:Link
UP BROADCAST RUNNING PROMISC MULTICAST MTU:1500 Metric:1
RX packets:330652 errors:0 dropped:0 overruns:0 frame:0
TX packets:343397 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000 
RX bytes:169157110 (169.1 MB) TX bytes:75439675 (75.4 MB)

lo Link encap:Local Loopback 
inet addr:127.0.0.1 Mask:255.0.0.0
inet6 addr: ::1/128 Scope:Host
UP LOOPBACK RUNNING MTU:65536 Metric:1
RX packets:785404 errors:0 dropped:0 overruns:0 frame:0
TX packets:785404 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0 
RX bytes:47633173 (47.6 MB) TX bytes:47633173 (47.6 MB)

tap_axp1 Link encap:Ethernet HWaddr 00:ac:ac:fd:31:28 
inet addr:192.168.10.1 Bcast:192.168.10.255 Mask:255.255.255.0
inet6 addr: fe80::2ac:acff:fefd:3128/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:5 errors:0 dropped:0 overruns:0 frame:0
TX packets:31 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:500 
RX bytes:298 (298.0 B) TX bytes:1818 (1.8 KB)

tap_axp2 Link encap:Ethernet HWaddr 00:ac:4a:cf:93:1f 
inet addr:192.168.20.1 Bcast:192.168.20.255 Mask:255.255.255.0
inet6 addr: fe80::2ac:4aff:fecf:931f/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:2 errors:0 dropped:0 overruns:0 frame:0
TX packets:13 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:500 
RX bytes:172 (172.0 B) TX bytes:1062 (1.0 KB)

now what i need ?

all i need is if the source ip was from subnet ip 192.168.10.0/24 i want to send it to socks 1

if source ip was from ip 192.168.20.0/24 i want it to go to socks 2

here is my config
root@VPNSOCKS:~# /etc/init.d/redsocks restart

Restarting redsocks redsocks ...done. root@VPNSOCKS:~# ======================== root@VPNSOCKS:~# /etc/init.d/redsocks restart
Restarting redsocks redsocks ...done. root@VPNSOCKS:~# cat /etc/redsocks.conf

base { 
log_debug = on; 
log_info = on;
redirector = iptables; }
redsocks {

ip =xx.66.10;
port = 1221;

// known types: socks4, socks5, http-connect, http-relay
type = socks5;

}
//////////////////////////////////
redsocks {
ip = xxx.66.11;
port = 1221;
type = http-connect;


}
redudp {

local_ip = 127.0.0.1;
local_port = 10053;
ip = 192.0.2.1;
port = 1080;
login = username;
password = pazzw0rd;
dest_ip = 192.0.2.2;
dest_port = 53;

udp_timeout = 30;
udp_timeout_stream = 180;
}

dnstc {
local_ip = 127.0.0.1;
local_port = 5300;
}

iptables rules :
sudo iptables -t nat -N REDSOCKS

sudo iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
sudo iptables -t nat -A REDSOCKS -p tcp -s 192.168.10.0/24 --dport 80 -j REDIRECT --to-ports 12345
sudo iptables -t nat -A REDSOCKS -p tcp -s 192.168.20.0/24 --dport 80 -j REDIRECT --to-ports 12346
sudo iptables -t nat -A OUTPUT -p tcp -o eth0 -j REDSOCKS

with the config above , it dont work and i cant tunnel tcp tunnel http traffic to the 2 socks servers i have !!! ??
i want to know what i need to do ?

**Comment by drvirusz** [comment]
hello guys any help ?

**Comment by darkk** [comment]
@drvirusz it seems to be configured correctly.

If you want to have additional comments, please provide following info:

1) pcap from `tcpdump -i eth0 'host pro.xy.addr.ess or host desti.nation.addr.ess'`
2) pcap from `tcpdump -i tap_axp1 'host pro.xy.addr.ess or host desti.nation.addr.ess'`
3) pcap from `tcpdump -i tap_axp1 'host pro.xy.addr.ess or host desti.nation.addr.ess'`
4) netfilter rules dump provided by `iptables-save` and `ip6tables-save`

All three pcap dumps should be uploaded to https://www.cloudshark.org/ to ease commenting. All three dumps should be captured at the same time while testing if setup works properly.

You should also tell how you test if it works – the best method is to run single `curl` request to some URL.

**Comment by darkk** [comment]
Closing it as it's basically an example of policy that may be handled by fake DNS resolver that will transmit FQDN to proxy (#23).
