### ISSUE TITLE
SOL_IP is not defined when compiling on MacOS 10.8.2

### ISSUE THREAD

**Issue by ingojaeckel** [darkk/redsocks#42]
I just grabbed the latest version of redsocks and tried to build it on MacOS 10.8.2. There were a number of compilation errors all caused by SOL_IP not being declared. Am I missing any libraries or should this be declared by the makefile?

FYI: I temporarily worked around the issue by adding "-DSOL_IP=IPPROTO_IP" to the CFLAGS in the Makefile. This at least allowed me to compile & run redsocks.

**Comment by darkk** [comment]
I have no permanent root access to machines running MacOSX to test and develop for this platform. Was v0.4 ever working on MacOSX? If it was, can you please contribute documentation with working MacOSX firewall configuration guidelines?

Also, I'm closing this issue in favor of #75 that tracks current MacOSX support status.
