### ISSUE TITLE
Fallback IP

### ISSUE THREAD

**Issue by antenore** [darkk/redsocks#48]
Where I work they use an old version (or a modified one) of redsocks that feature a fallback ip option (fip= in the redsocks.conf).

Are you aware of this option? How does it works? How can I implement it with the last version of redsocks?

Thanks in advance!!!!!

**Comment by antenore** [comment]
Closing... I'm going to open a new one.

**Comment by darkk** [comment]
Anyway, I'm unaware of this option and IMHO haproxy / IPVS is usually a better solution option for failover.

**Comment by antenore** [comment]
What do you mean please? I don't know haproxy/IPVS is something I can use on client side? 

To just clarify, this issue is related to the PR #49 (never merged for good reasons probably) that I submitted a long time ago, to simplify the setup where we work.

We have part of the socks servers that are available only from the office LAN, when we connect from home we have to use other SOCKS servers, that's why we use that patch.

That way redsocks try to connect to the first SOCKS server, if it goes in timeout it uses the fallback one.

PLease let me know if I have to better explain the scenario, I'm not good at explanation :-) 

For us it's just a workaround, so if you have a better solution to advice, except having two different redsocks.conf files, I prefer as well, because the patch I submitted it's not so good... It's just a workaround (and I cannot make it to work with the last codebase). 

Thanks in advance!!!!!!!!

**Comment by darkk** [comment]
@antenore this use-case can be handled using various methods

1. haproxy, having two upstreams and selecting "alive" one. It will work if socks5 login/password is same for both proxies.
2. detecting the environment and restarting redsocks with proper config file
3. detecting the environment and changing `iptables` ruleset to match the environment having redsocks running with two `redsocks { .... }` sections in the config file

My usual setup is environment-based. It's quite easy to do that with network-manager dispatcher scripts and network-manager is de facto standard for Linux desktop network configuration.

**Comment by antenore** [comment]
Yes, it make sense.

Thanks a lot.
