### ISSUE TITLE
A little help on UDP redirection

### ISSUE THREAD

**Issue by lepasserby** [darkk/redsocks#59]
Hi! 
Shadowsocks user here.

Shadowsocks apparently has redsocks under the hood, so I decided to go here in hope of some englightment.

Usecase:
1) Force UDP AND TCP traffic that is going to a specific remote port to go through the proxy
2) Force UDP AND TCP traffic originating from a specific port range to go through the proxy

Why: 
Impromptu SIP/VoIP hardening (because DTLS implementation on my softphone and my TURN server sucks royally)

**Comment by darkk** [comment]
Closing as #12 duplicate as these two use-cases may be handled by corresponding iptables configuration.
That's basically implemented long time ago, but has non-trivial configuration.
