### ISSUE TITLE
Possible group name issue on Debian

### ISSUE THREAD

**Issue by steelee** [darkk/redsocks#60]
Redsocks compiles just fine on my Debian installation, but there is an issue if I try to run it. Not sure if this is limited to just a specific version of Debian (mine is 8.1) but I reproduced this issue on several machines. When I try to run it, I get this message:
`$ ./redsocks -c redsocks.conf`
`1436994266.548607 base.c:352 base_init(...) getgrnam(nobody): Success`
And no workers start up for Redsocks. Printing out the input to `getgrnam(group)`, I noticed that the group value is `nobody`, which is not a valid group. By changing the input to `nogroup`, I was able to start Redsocks.

**Comment by darkk** [comment]
Thanks :)
