### ISSUE TITLE
UDP not working

### ISSUE THREAD

**Issue by madhanraj** [darkk/redsocks#61]
Redsocks does not work with UDP . 
REDUDP configured but doesnt work in client side .

**Comment by darkk** [comment]
That's hard to help you without following information – your OS, routing & firewall configuration, redsocks.conf.

**Comment by madhanraj** [comment]
I am trying to use a proxy client with UDP case . In TCP case with redirection and NAT rules it is perfect . But in UDP I am not sure exactly how the client would work in case of connection less proto. The prerouting iptables rules with Tproxy would be on the middlebox or the end server . Can you please specify the exact steps to configure UDP in the proxy Client .

I am using conf same as redsocks.conf.example 
OS : Linux 3.10 Saucy

A good configuration guide for enabling UDP proxy client would be of great help . .

**Comment by darkk** [comment]
Closing as #12 duplicate.
