### ISSUE TITLE
arch - systemd environment file fail

### ISSUE THREAD

**Issue by TaiSHiNet** [darkk/redsocks#62]
In redoscks.service it says:
EnvironmentFile=/etc/conf.d/redsocks

But this file is not created by default.

**Comment by anselmolsm** [comment]
I'd say it's a packaging issue. As the current maintainer of redsocks-git package on AUR, I added a rule to create such file in packaging time.

**Comment by darkk** [comment]
@anselmolsm thanks! :-)
