### ISSUE TITLE
Redsocks doesn't work with the ssh -D command

### ISSUE THREAD

**Issue by hillz1** [darkk/redsocks#65]
I use this ssh tunnel command to create a socks proxy on my openwrt router with the IP of 192.168.1.1:

ssh -o "ProxyCommand corkscrew 127.0.0.1 3339 %h %p" -vND 1080 username@serverip

and this is my redsocks.conf:

```
base {
        // debug: connection progress & client list on SIGUSR1
        log_debug = on;

        // info: start and end of client session
        log_info = on;

        /* possible `log' values are:
         *   stderr
         *   file:/path/to/file
         *   syslog:FACILITY  facility is any of "daemon", "local0"..."local7"
         */
        log = stderr;

        // detach from console
        daemon = off;

        /* Change uid, gid and root directory, these options require root
         * privilegies on startup.
         * Note, your chroot may requre /etc/localtime if you write log to syslog.
         * Log is opened before chroot & uid changing.
         */
        // user = nobody;
        // group = nobody;
        // chroot = "/var/chroot";

        /* possible `redirector' values are:
         *   iptables   - for Linux
         *   ipf        - for FreeBSD
         *   pf         - for OpenBSD
         *   generic    - some generic redirector that MAY work
         */
        redirector = iptables;
}

redsocks {
        /* `local_ip' defaults to 127.0.0.1 for security reasons,
         * use 0.0.0.0 if you want to listen on every interface.
         * `local_*' are used as port to redirect to.
         */
        local_ip = 0.0.0.0;
        local_port = 12345;

        // `ip' and `port' are IP and tcp-port of proxy-server
        ip = 127.0.0.1;
        port = 1080;


        // known types: socks4, socks5, http-connect, http-relay
        type = socks5;

        // login = "foobar";
        // password = "baz";
}

redudp {                                                         
        // `local_ip' should not be 0.0.0.0 as it's also used for outgoing
        // packets that are sent as replies - and it should be fixed      
        // if we want NAT to work properly.                               
        local_ip = 127.0.0.1;                                             
        local_port = 10053;                                               

        // `ip' and `port' of socks5 proxy server.                        
        ip = 127.0.0.1;                                                   
        port = 1080;                                                      
        //login = username;                                               
        //password = pazzw0rd;                                            

        // kernel does not give us this information, so we have to duplicate it
        // in both iptables rules and configuration file.  By the way, you can 
        // set `local_ip' to 127.45.67.89 if you need more than 65535 ports to 
        // forward ;-)                                                         
        // This limitation may be relaxed in future versions using contrack-tools.
        dest_ip = 8.8.8.8;                                                        
        dest_port = 53;                                                           

        udp_timeout = 30;                                                         
        udp_timeout_stream = 180;                                                 
}                                                                                 

// you can add more `redsocks' and `redudp' sections if you need.
```

How can I use redsocks to redirect my internet traffic to that ssh tunnel ? I want it to be like openvpn where I can just connect to my wifi and browse the internet, with ssh tunnel I have to set the proxy to socks port 1080 on the client side every time I want to redirect all my internet traffic to that tunnel. I'm new to linux and I'm stuck at the iptables command, I have read the instructions at http://darkk.net.ru/redsocks/ but I still can't get it to work. Here's the commands I use:

```
iptables -t nat -N REDSOCKS
iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -p tcp -j DNAT --to-destination 127.0.0.1:12345
iptables -t nat -I OUTPUT 1 -p tcp -j REDSOCKS
iptables -t nat -I PREROUTING 1 -p tcp -s 192.168.1.0/22 -j REDSOCKS
```

Please tell me where I went wrong.

**Comment by darkk** [comment]
> How can I use redsocks to redirect my internet traffic to that ssh tunnel

You should probably use `REDIRECT` instead of `DNAT`.

> I want it to be like openvpn

That's (strictly speaking) impossible. `openvpn` works at MAC or IP layer and `redsocks` works at TCP layer. Moreover, `redsocks`+`ssh` will encapsulate several TCP streams to single ssh stream, and it may be bad for latency due to [Head-of-line blocking](https://en.wikipedia.org/wiki/Head-of-line_blocking).

But it should work **a-bit-like** openvpn if you can tolerate the latency.

**Comment by hillz1** [comment]
As you suggested, I tried:

iptables -t nat -N REDSOCKS
iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-destination 127.0.0.1:12345
iptables -t nat -I OUTPUT 1 -p tcp -j REDSOCKS
iptables -t nat -I PREROUTING 1 -p tcp -s 192.168.1.0/22 -j REDSOCKS

But I got an error: 

iptables v1.4.21: unknown option "--to-destination"
Try `iptables -h' or 'iptables --help' for more information.

I just want my clients to be able to browse the internet without having to set up socks proxy on their browsers. Of course their traffic should be redirected through that ssh tunnel. I have no access for shell commands on the server side that's why I can only use redsocks, I know there's tun2socks / sshuttle but they both require you to have access of shell commands on the server side.

The redsocks log doesn't show anything: http://s9.postimg.org/od41idhkf/72652l.jpg

**Comment by darkk** [comment]
You should probably read (man iptables-extensions(8))[http://ipset.netfilter.org/iptables-extensions.man.html].

`REDIRECT` target does not support `--to-destination` option, it uses `--to-ports`. So the rule should look like that: `iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports 12345`

**Comment by hillz1** [comment]
It still doesn't work and the redsocks log doesn't show anything again, how can I troubleshoot iptables? Is there a log file I can look into to find out what's wrong? Sorry for troubling you so much, I'm not a computer expert.

**Comment by darkk** [comment]
> how can I troubleshoot iptables

You can use [TRACE target](http://ipset.netfilter.org/iptables-extensions.man.html#lbDZ) to log all matched rules to dmesg. Or you can reset all counters using `iptables -Z`, pass some traffic and look at counters via `iptables-save --counters`. Maybe some zero (or non-zero) counter will highlight the error.
