### ISSUE TITLE
request a UDP with TPROXY iptables example

### ISSUE THREAD

**Issue by MiniLight** [darkk/redsocks#67]
I cannot find a UDP with TPROXY iptables example in redsocks's documents. "redudp" part In  redsocks.conf imply redsocks is able to redirect UDP packets, but I don't know how to implement that.

If possible, please provide a example of iptables in redirect UDP packets.

Thank you.

**Comment by shellus** [comment]
redudp only forward DNS request，To a fixed destination。
redudp does not mean that you can use redsocks to forward udp

**Comment by MiniLight** [comment]
I see, thank you

**Comment by shellus** [comment]
and you see: 

```
ip rule add fwmark 0x01/0x01 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N SSUDP
iptables -t mangle -A SSUDP -p udp -j TPROXY --on-port 20000 --tproxy-mark 0x01/0x01
iptables -t mangle -A PREROUTING -j SSUDP
```
via: http://blog.csdn.net/lvshaorong/article/details/53203674

**Comment by shellus** [comment]
try ss-redir: https://github.com/clowwindy/shadowsocks-libev/tree/master#advanced-usage

**Comment by ge9** [comment]
Yes, redsocks can redirect UDP packets to arbitrary destinations.
https://github.com/darkk/redsocks/issues/12
