### ISSUE TITLE
Compile redsocks for Android using android NDK

### ISSUE THREAD

**Issue by yanggis** [darkk/redsocks#74]
I got this error when compiling redsocks using Android NDK:

E:\Android_SDK\android-ndk-r10e\redsocks-0.4\android>ndk-build
[armeabi] Compile thumb  : redsocks <= parser.c
[armeabi] Compile thumb  : redsocks <= main.c
[armeabi] Compile thumb  : redsocks <= redsocks.c
[armeabi] Compile thumb  : redsocks <= log.c
[armeabi] Compile thumb  : redsocks <= http-connect.c
[armeabi] Compile thumb  : redsocks <= socks4.c
[armeabi] Compile thumb  : redsocks <= socks5.c
[armeabi] Compile thumb  : redsocks <= http-relay.c
[armeabi] Compile thumb  : redsocks <= base.c
jni/../../base.c:28:20: fatal error: config.h: No such file or directory
 #include "config.h"

Any tips? thanks!

**Comment by timoshenkoav** [comment]
pull config.h from https://github.com/ventureresearch/libevent/blob/patches-2.0/android/event2/config.h and copy to jni/libevent

**Comment by yanggis** [comment]
Hi Timoshenkoav, thanks for the response.
I've compiled redsocks with android NDK 10e, but now I have another issue.
When I run the binary on Android 5.1, I got this error:"only position independent executables (PIE) are supported.".
I've triedd to add 

LOCAL_CFLAGS += -fPIE
LOCAL_LDFLAGS += -fPIE -pie

to Android.mk, and re-compiled again, but no luck.

How to compile redsocks with/without flag of fPIE for Android (<4.1) and Android (4.1+) respectively?
Thanks.

**Comment by timoshenkoav** [comment]
i have 
LOCAL_CFLAGS += -fPIE 
LOCAL_LDFLAGS += -fPIE -pie
in Android.mk, and it works for me, maybe try to clean\rebuild. Or you want to have 2 executables? With and without PIE?

**Comment by yanggis** [comment]
Hi timoshenkoav, thanks for your kind response.
You could be right because I havent tried to clean\rebuild. 
Yes, I need to executables, one without fPIE flag for Android 4.0, another one with fPIE for Android 4.1+.

**Comment by timoshenkoav** [comment]
if you need two executables you can have 2 android.mk (1 for <4.0 and >4.0) with different executable name and different configs, or you can build it once and copy for example to res/raw or assets and then extract by code.

**Comment by yanggis** [comment]
Got it. Thanks.

**Comment by vaibhavreddys** [comment]
@yanggis , Can you please share the redsocks binary for Android devices preferably with Android version 5 and above?

(It would be very much helpful for me)

**Comment by clouedoc** [comment]
For future reference: you can extract Android redsocks binary from the ProxyDroid apk. (simply unzip it and search for a file named `redsocks`)

**Comment by Jackychans** [comment]
> For future reference: you can extract Android redsocks binary from the ProxyDroid apk. (simply unzip it and search for a file named `redsocks`)

It seems proxyDroid redsocks version is 0.4, not the latest one, thus, does not support dnstc feature

Anyone please can share redsocks 0.5 ?
