### ISSUE TITLE
What does "dropping client" mean in redsocks log ?

### ISSUE THREAD

**Issue by hillz1** [darkk/redsocks#77]
I get this every time I use redsocks:
`1458074267.645139 redsocks.c:322 redsocks_start_relay(...) [192.168.1.203:54201->103.6.117.2:80]: data relaying started
1458074283.698802 redsocks.c:395 redsocks_shutdown(...) [192.168.1.203:54201->103.6.117.2:80]: both client and server disconnected
1458074283.699201 redsocks.c:332 redsocks_drop_client(...) [192.168.1.203:54201->103.6.117.2:80]: dropping client`

What does that error mean ?

**Comment by darkk** [comment]
It's not an error, it's just start/stop of client connection. You can turn it off using `log_debug = false` and `log_info = false`.

`log_debug` enables information logged with LOG_DEBUG severity — it's some debugging info about connection progress.
`log_info` enables LOG_INFO messages — end / start / errors of client session.
