### ISSUE TITLE
Link redsocks in the AUR website is not found

### ISSUE THREAD

**Issue by hillz1** [darkk/redsocks#82]
In your README file you mention that https://aur.archlinux.org/packages.php?ID=41765 is the link to redsocks, but it's gone, perhaps you should submit redsocks to AUR again. I can't find redsocks anywhere in the AUR website.

**Comment by darkk** [comment]
I don't use Arch Linux myself. The link was fresh [half a year ago](https://web.archive.org/web/20150804072445/https://aur.archlinux.org/packages.php?ID=41765).
Proper link seems to be https://aur.archlinux.org/packages/redsocks-git

Also, it seems to me, that the package `0.1.r43.g2e3f648-1` should actually have version `0.4`:

```
$ git describe 2e3f648
release-0.1-43-g2e3f648
$ git describe --tags 2e3f648
release-0.4-16-g2e3f648
```
