### ISSUE TITLE
speed limitation?

### ISSUE THREAD

**Issue by zoobab** [darkk/redsocks#86]
Hi,

I have the impression that redsocks has some speed limitations, what it the highest speed where it has been tested? I can't go higher then 2MB/sec, I don't know if other people have the same problem.

**Comment by darkk** [comment]
Hi. Is it 2Mbits/sec or 2Mbytes/sec? Is CPU usage 100% during the test? What's your testing method?

I've recently tested `redsocks` on OpenWRT box and got ~40 Mbit/s through single connection after adding `splice()` in af46180272295b46d1e455944295b3b6f24f40a2. OTOH, having 400 100kbit/s connections may produce different results.

**Comment by L4R5** [comment]
Hi. I had about 11 MB/s on a 100 MBit link in the past.

2016-06-13 15:55 GMT+02:00 Leonid Evdokimov <notifications@github.com>:

**Comment by darkk** [comment]
Just for the record, I've got that datapoint:

> 40 Mbit/s on [TP-Link TD-W8980](https://wiki.openwrt.org/toh/tp-link/td-w8980) using splice()
