### ISSUE TITLE
dynamic UDP proxying on android devices with no TPROXY iptables target?

### ISSUE THREAD

**Issue by tonsimple** [darkk/redsocks#87]
Hi!
Quick question, is it possible to do dynamic UDP redirection for a case where tproxy is not available and knowing the exact IP/port of destination is not an option?

USECASE:

Tunnel OpenVPN (ics-openvpn which supports socks-proxy directive) over Shadowsocks on android

**Comment by semigodking** [comment]
No.
2016年6月24日 上午12:05，"Simply Sarah" <notifications@github.com>写道：

**Comment by darkk** [comment]
I've updated README with some more info on mobile devices:

> When is redsocks probably a wrong tool?
> * redirecting traffic to proxy on mobile device running Android or iOS as it'll require  [rooting](https://en.wikipedia.org/wiki/Rooting_(Android)) to update firewall  rules. Probably, the better way is to use on-device VPN daemon to intercept   traffic via [`VpnService` API for Android](https://developer.android.com/reference/android/net/VpnService.html)  and [`NETunnelProvider` family of APIs for iOS](https://developer.apple.com/documentation/networkextension).   That may require some code doing [TCP Reassembly](https://wiki.wireshark.org/TCP_Reassembly)  like [`tun2socks`](https://github.com/ambrop72/badvpn/wiki/Tun2socks).
