### ISSUE TITLE
compilation error from linux

### ISSUE THREAD

**Issue by uzmanager** [darkk/redsocks#9]
When I try to compile source I get message:
root@linux:/home/test/1/darkk-redsocks-2b6dcc8# make
cc -g -O2 -std=gnu99 -Wall   -c -o redsocks.o redsocks.c
redsocks.c: In function 'redsocks_log_write_plain':
redsocks.c:185: error: dereferencing pointer to incomplete type
make: **\* [redsocks.o] Error 1

My gcc version is 

root@linux:/home/test/1/darkk-redsocks-2b6dcc8# gcc -v
Using built-in specs.
Target: i486-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.3.3-5ubuntu4' -
-with-bugurl=file:///usr/share/doc/gcc-4.3/README.Bugs --enable-languages=c,c++,
fortran,objc,obj-c++ --prefix=/usr --enable-shared --with-system-zlib --libexecd
ir=/usr/lib --without-included-gettext --enable-threads=posix --enable-nls --wit
h-gxx-include-dir=/usr/include/c++/4.3 --program-suffix=-4.3 --enable-clocale=gn
u --enable-libstdcxx-debug --enable-objc-gc --enable-mpfr --enable-targets=all -
-with-tune=generic --enable-checking=release --build=i486-linux-gnu --host=i486-
linux-gnu --target=i486-linux-gnu
Thread model: posix
gcc version 4.3.3 (Ubuntu 4.3.3-5ubuntu4)

uname -a
root@linux:/home/test/1/darkk-redsocks-2b6dcc8# uname -a
Linux colinux 2.6.33.7-co-0.7.9 #1 PREEMPT Mon Jan 31 22:17:54 UTC 2011 i686 GNU
/Linux

**Comment by darkk** [comment]
@ywnzzl as far as I see, [Centos 6 reached end-of-life](https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule) in terms of "full updates" a year ago.
