### ISSUE TITLE
add proxi list

### ISSUE THREAD

**Issue by nekulin** [darkk/redsocks#93]
How to add proxy in proxychains
specify random_chain

**Comment by darkk** [comment]
`redsocks` is not `proxychains`, `redsocks` works at firewall level and `proxychains` works at per-process level using LD_PRELOAD.

You can technically build something like chain of proxies having several redsocks daemons handling each others traffic. Randomization can be implemented at firewall level as well using any of load balancing methods.

**Comment by nekulin** [comment]
as an example of how to make friends ? I tried to run proxychains4 /bin/squid but something is not working properly.

**Comment by darkk** [comment]
Trivial pre-hop randomization may be done by `iptables` (see #94).

Also, IMHO, you should not mix LD_PRELOAD solutions with event-based daemons (squid, nginx, redsocks) as it's not trivial to implement libc wrapper that will fit nicely in event-based runloop.

Chaining may be done using different trick, each "layer" should be separate `redsocks` instance and these instances should be handling each others' traffic. These instances can be run under separate UIDs to filter corresponding traffic at firewall level using iptables `owner` module.

Anyway, I'm unsure if proxy chaining is really the solution for the problem you're actually trying to solve. :)
