### ISSUE TITLE
0.5 fails to build on macOS

### ISSUE THREAD

**Issue by nijikon** [darkk/redsocks#96]
https://gist.github.com/a38f0662b03d45d9bff942860020847a

**Comment by darkk** [comment]
@nijikon was 0.4 ever working on MacOS? I had no chance to test it.

**Comment by nijikon** [comment]
@darkk compiles without issues https://gist.github.com/1e4acd9757d86ecdd81fcbdd2a2f9390

**Comment by fxcoudert** [comment]
This seems to be the same as https://github.com/darkk/redsocks/issues/75
This is due to building with `-D_XOPEN_SOURCE=600`, which prevents darwin's `<netinet/in.h>` to define `INADDR_LOOPBACK`.

**Comment by ilovezfs** [comment]
ping.

**Comment by ilovezfs** [comment]
ping on this

**Comment by darkk** [comment]
@ilovezfs I have no permanent root access to machines running MacOSX to test and develop for this platform. Was v0.4 ever working on MacOSX? Can you please contribute documentation with working MacOSX firewall configuration guidelines?

**Comment by darkk** [comment]
Closing as duplicate in favor of #75.
