### ISSUE TITLE
can redsocks be used in application level?

### ISSUE THREAD

**Issue by brianwang** [darkk/redsocks#98]
I just  guess can redsocks be used not in wide system leve, just like an application or a service on linux* system? anything is adviced.....

**Comment by darkk** [comment]
No.
The whole point of redsocks is that it's firewall-level "proxifier" (intercepting packets), not "application-level" (intercepting libc calls). So it works with statically linked binaries and binaries doing direct calls to kernel bypassing libc wrappers.
On the other hand, you can distinguish applications at firewall level putting them to different `net_cls` cgroups, different network namespaces or running then with different uid/gid.

**Comment by brianwang** [comment]
thx so much.
